services:
  - type: web
    name: hianime-api
    env: bun
    region: oregon
    plan: free
    buildCommand: bun install
    startCommand: bun index.js
    envVars:
      - key: PORT
        value: 10000
